[package]
name = "rtmp-plugin"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
obs= { path = "../obs" }
rml_rtmp = "0.3.0"
slab = "0.4.0"
bytes = "0.5"

[lib]
name = "rtmpplugin"
crate-type = ["cdylib"]
