[package]
name = "copernica-plugin"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
obs= { path = "../obs" }

[lib]
name = "copernicaplugin"
crate-type = ["cdylib"]
